spring:
  application:
    name: boot

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: invade
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL8InnoDBDialect

server:
  port: 8080
  servlet:
    context-path: /springboot
  session:
    timeout: 60