spring:
  application:
    name: boot

  datasource:
    url: jdbc:mysql://courser.mycloudnas.com:23306/springboot?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: invade
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 60s

